# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: condition
    type: boolean
    default: true
  - name: stageName
    default: uncontrolled
    values:
      - controlled
      - uncontrolled

stages:
  - stage: initialization
    displayName: Pipeline start initialization
    jobs: 
      - job: initialization_job
        displayName: Initialization Job
        steps:
          - template: pipelines/initialization_job.yml

  - stage: build_artifact
    displayName: Start build artifacts
    dependsOn: initialization
    condition: and(succeeded(), ${{parameters.condition}})
    jobs:
      - job: prepare_build_env
        displayName: Prepare Build environment
        steps:
          - template: pipelines/build_artifact_job.yml

  - template: pipelines/deployment.yml