parameters:
  - name: p1
    type: string
    default: hello
  - name: p2
    type: boolean
    default: true

steps:
  - task: Bash@3
    displayName: Start Deployment
    inputs:
      targetType: 'inline'
      script: |
         echo "start deployment...."